### ISSUE TITLE
pycocotools import issue

### ISSUE THREAD

**Issue by zenccc** [2017-fall-DL-training-program/ImageCaption#10]
hello, 
I got the error message "ImportError: No module named pycocotools.coco", it is coming from eval_utils.py #line 32, any idea about this? I am sure that it run with python 2.7.

**Comment by connie980149** [comment]
Did you copy the ./coco_caption to your work space?

**Comment by fansia** [comment]
I have written a letter to IT to install this lib for us last Friday(11/10).

**Comment by connie980149** [comment]
I remember that IT had downloaded the coco_caption, maybe you can try to find it under /homework/datasets.

**Comment by fansia** [comment]
quoted from email:
---------------------------------------------------
Hi, Eric, 

我們發現助教給的dataset裡面就有pycocotools, 

請把datasets/coco-caption設定在你的pythonpath內既可:
Ex: @tcsh
setenv PYTHONPATH ~/datasets/coco-caption/
echo $PYTHONPATH
/home/student47/datasets/coco-caption/

>:~/datasets/coco-caption% python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pycocotools.coco import COCO
>>> 
>>> dir(COCO)
['__doc__', '__init__', '__module__', 'createIndex', 'decodeMask', 'encodeMask', 'getAnnIds', 'getCatIds', 'getImgIds', 'info', 'loadAnns', 'loadCats', 'loadImgs', 'loadRes', 'segToMask', 'showAnns']
