### ISSUE TITLE
Question about self.h2rnn and self.att2rnn

### ISSUE THREAD

**Issue by Peter-Chuang** [2017-fall-DL-training-program/ImageCaption#11]
Dear TA,

In class ShowAttendTellCore(nn.Module), there are two functions called
        self.h2rnn = nn.Linear(self.input_encoding_size, self.rnn_size)
        self.att2rnn = nn.Linear(self.att_feat_size, self.rnn_size)
What are these for?

Peter

**Comment by connie980149** [comment]
Those are redundant codes, don't care about them.
I forgot to delete them, sorry.

**Comment by Peter-Chuang** [comment]
Got it. THanks.
