### ISSUE TITLE
utf-8 decode error

### ISSUE THREAD

**Issue by mtkmark** [2017-fall-DL-training-program/ImageCaption#16]
Any one got utf issue while executing eval.py ? 

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
===========
Original exception was:
Traceback (most recent call last):
  File "eval.py", line 73, in <module>
    infos = cPickle.load(f)
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

**Comment by connie980149** [comment]
Because python3 removes the cPickle model, to slove this issue
1. use python2.7 or
2. replace cPickle by pickle (I'm not sure whether this way will cause other bugs)

**Comment by doom8199** [comment]
hi mtkmark:
    This error happened because your python tried to use utf-8 codec to open non-UTF-8 format file.
    It can be fixed by changing input binary format to "rb"

**Comment by mtkmark** [comment]
In Eval.py Line 73


with open(opt.infos_path,'rb') as f:
    infos = cPickle.load(f)
