### ISSUE TITLE
Dim of att

### ISSUE THREAD

**Issue by Puff-Wen** [2017-fall-DL-training-program/ImageCaption#3]
Hi TA,

in resnet_utils.py,  the forward function of Resnet, the dim of 
F.adaptive_avg_pool2d(x,[att_size,att_size]).squeeze()
is (10L, 2048L, 14L, 14L) which cannot be permute by permute(1, 2, 0).
Did I miss something? Thanks.

- Puff

**Comment by connie980149** [comment]
This lab take the output of layer4 in ResNet as CNN feature.
Use the ResNet from begin to layer4, there is no need to load the avgpool and fc layer.
