### ISSUE TITLE
Training setting of language_eval and val_images_use

### ISSUE THREAD

**Issue by Peter-Chuang** [2017-fall-DL-training-program/ImageCaption#6]
Dear TA,

What language should we use for evaluation and how many images should we use for validation?
The default setting of language_eval is 1 and val_images_use is 500.

Peter

**Comment by connie980149** [comment]
language_eval=1 meas the evaluation will call the COCO API to evaluate sentences.
The number of validation images for each time is recommended to use 500.

**Comment by Peter-Chuang** [comment]
So, should we use "--language_eval 0" or "--language_eval 1"?

**Comment by connie980149** [comment]
The training process will not be affected by this setting.
You can use "--language_eval 1" for evaluating the result and report it, it's based on your choice.

**Comment by Peter-Chuang** [comment]
Got it. Thank you!
