### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ericbillwang** [2017-fall-DL-training-program/ImageCaption#8]
Dear TA,
  Few questions
  1. In forward function of ShowAttendTellCore class
    - What's the meaning of fc_feats vs. att_feats & how it map to the lab guide document ?
    - It seems att_feats corresponding to V is coming from CNN model, is the understanding correct? 
      What's fc_feats mean ?
 
Thanks, Ericbill

**Comment by connie980149** [comment]
att_feats is the output of CNN (batch x 7 x 7 x 2048)
fc_feats takes average pooling on feature maps of att_feats (batch x 2048)
In the document, att_feats is 'V' and fc_feats is 'V bar'
